import React, { useState, useEffect } from 'react';
import { useLocation, Link, Navigate, useParams } from 'react-router-dom';
import { ArrowLeft, Printer, FileText, BookOpen, Edit, Save, X, Loader2 } from 'lucide-react';
import { db } from '../services/firebase';
import { doc, getDoc, updateDoc } from 'firebase/firestore';

const ProjectResult = () => {
  const location = useLocation();
  const { id } = useParams();

  // Initialize from state if available, otherwise null (will fetch)
  const [project, setProject] = useState(location.state?.project || null);
  const [isLoading, setIsLoading] = useState(!location.state?.project && !!id);
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // Edit state
  const [editTitle, setEditTitle] = useState('');
  const [editContent, setEditContent] = useState('');

  useEffect(() => {
    // If we have an ID but no project data, fetch it.
    if (id && !project) {
        const fetchProject = async () => {
            setIsLoading(true);
            try {
                const docRef = doc(db, 'projects', id);
                const docSnap = await getDoc(docRef);
                if (docSnap.exists()) {
                    const data = docSnap.data();
                    setProject({ id: docSnap.id, ...data });
                } else {
                    console.error("No such document!");
                }
            } catch (error) {
                console.error("Error fetching project:", error);
            } finally {
                setIsLoading(false);
            }
        };
        fetchProject();
    }
  }, [id, project]);

  // Sync edit state when project is loaded or edit mode toggled
  useEffect(() => {
      if (project) {
          setEditTitle(project.title);
          setEditContent(project.content);
      }
  }, [project, isEditing]);

  const handleSave = async () => {
      if (!project || !project.id) return;
      setIsSaving(true);
      try {
          const docRef = doc(db, 'projects', project.id);
          await updateDoc(docRef, {
              title: editTitle,
              content: editContent,
              lastEdited: "Just now" // In a real app, use serverTimestamp() or new Date().toISOString()
          });

          setProject(prev => ({
              ...prev,
              title: editTitle,
              content: editContent,
              lastEdited: "Just now"
          }));
          setIsEditing(false);
      } catch (error) {
          console.error("Error updating project:", error);
          alert("Failed to save changes.");
      } finally {
          setIsSaving(false);
      }
  };

  const handleDownloadWord = () => {
    const element = document.getElementById('project-content');
    if (!element) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${project.title}</title>
        <style>
          body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.5; color: #000; }
          h1 { text-align: center; font-size: 24pt; font-weight: bold; margin-bottom: 24px; text-transform: capitalize; }
          .header { text-align: center; border-bottom: 1px solid #000; margin-bottom: 30px; padding-bottom: 20px; }
          .meta { font-size: 10pt; color: #555; text-align: center; margin-bottom: 10px; }
          .content { text-align: justify; white-space: pre-wrap; }
          .footer { margin-top: 50px; font-size: 9pt; text-align: center; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
           <p style="text-transform: uppercase; font-weight: bold; font-size: 10pt;">Department of ${project.category}</p>
           <h1>${project.title}</h1>
           <div class="meta">
             <p><strong>Student Name:</strong> Student Name | <strong>Matric:</strong> HNG-102-44</p>
             <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
           </div>
        </div>
        <div class="content">
          ${project.content}
        </div>
        <div class="footer">
          Generated by ProjectBuddy AI
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${project.title.replace(/\s+/g, '_')}_Assignment.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
      return (
          <div className="min-h-screen flex items-center justify-center bg-gray-200">
              <Loader2 className="animate-spin text-blue-600" size={40} />
          </div>
      );
  }

  if (!project) {
    if (!id) return <Navigate to="/" replace />;
    return (
        <div className="min-h-screen flex items-center justify-center bg-gray-200">
            <p className="text-gray-600">Project not found.</p>
             <Link to="/" className="ml-4 text-blue-600 hover:underline">Go Home</Link>
        </div>
    );
  }

  const formattedDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="min-h-screen bg-gray-200 py-6 md:py-10 px-2 md:px-4 font-sans print:bg-white print:p-0">
      
      {/* --- TOOLBAR --- */}
      <div className="w-full md:max-w-[210mm] mx-auto mb-6 flex flex-col md:flex-row justify-between items-center gap-4 print:hidden">
        <Link to="/" className="inline-flex items-center text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors self-start md:self-auto">
          <ArrowLeft size={16} className="mr-2" />
          Back to Dashboard
        </Link>
        
        <div className="flex flex-wrap gap-3 w-full md:w-auto">
             {/* Edit / Save Buttons */}
             {isEditing ? (
                <>
                    <button
                        onClick={() => setIsEditing(false)}
                        className="flex items-center justify-center gap-2 px-4 py-2.5 bg-white text-gray-700 border border-gray-200 rounded-lg hover:bg-gray-50 shadow-sm transition-all font-medium text-xs md:text-sm"
                        disabled={isSaving}
                    >
                        <X size={16} /> Cancel
                    </button>
                    <button
                        onClick={handleSave}
                        className="flex items-center justify-center gap-2 px-4 py-2.5 bg-green-600 text-white rounded-lg hover:bg-green-700 shadow-md transition-all font-medium text-xs md:text-sm"
                        disabled={isSaving}
                    >
                        {isSaving ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}
                        Save Changes
                    </button>
                </>
            ) : (
                <button
                    onClick={() => setIsEditing(true)}
                    className="flex items-center justify-center gap-2 px-4 py-2.5 bg-white text-blue-700 border border-blue-200 rounded-lg hover:bg-blue-50 shadow-sm transition-all font-medium text-xs md:text-sm"
                >
                    <Edit size={16} /> Edit Document
                </button>
            )}

            <button 
                onClick={handleDownloadWord}
                className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-white text-blue-700 border border-blue-200 rounded-lg hover:bg-blue-50 shadow-sm transition-all font-medium text-xs md:text-sm"
            >
                <FileText size={16} /> <span className="hidden sm:inline">Download as</span> Word
            </button>

            <button 
                onClick={() => window.print()}
                className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 shadow-md transition-all font-medium text-xs md:text-sm"
            >
                <Printer size={16} /> Print
            </button>
        </div>
      </div>

      {/* --- THE PAPER DOCUMENT --- */}
      <div id="project-content" className="w-full md:max-w-[210mm] mx-auto bg-white shadow-2xl min-h-[297mm] p-6 md:p-[25mm] relative print:shadow-none print:w-full print:max-w-none print:p-[20mm] print:m-0">
        
        {/* HEADER */}
        <div className="text-center border-b-4 border-double border-gray-800 pb-6 mb-10">
            <div className="flex justify-center mb-4 text-gray-800">
                <BookOpen size={36} md:size={48} strokeWidth={1.5} />
            </div>
            
            <p className="text-xs md:text-sm font-bold tracking-[0.2em] uppercase text-gray-600 mb-4">
                Department of {project.category === 'Business' ? 'Business Administration' : project.category === 'Academic' ? 'General Studies' : 'Personal Development'}
            </p>
            
            {isEditing ? (
                <input
                    type="text"
                    value={editTitle}
                    onChange={(e) => setEditTitle(e.target.value)}
                    className="w-full text-center text-3xl md:text-5xl font-bold text-gray-900 mb-6 leading-tight font-serif capitalize border-b-2 border-blue-300 focus:outline-none focus:border-blue-600 bg-gray-50 p-2 rounded"
                />
            ) : (
                <h1 className="text-3xl md:text-5xl font-bold text-gray-900 mb-6 leading-tight font-serif capitalize">
                    {project.title}
                </h1>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-sm mt-8 border-t border-gray-200 pt-6">
                <div className="text-center">
                    <p className="font-bold uppercase tracking-wider text-[10px] text-gray-500 mb-1">Submitted By</p>
                    <div className="font-serif text-gray-900 text-base">Student Name</div>
                </div>
                
                <div className="text-center border-t sm:border-t-0 sm:border-l sm:border-r border-gray-200 pt-4 sm:pt-0">
                    <p className="font-bold uppercase tracking-wider text-[10px] text-gray-500 mb-1">Matric Number</p>
                    <div className="font-serif text-gray-900 text-base">HNG-102-44</div>
                </div>

                <div className="text-center border-t sm:border-t-0 border-gray-200 pt-4 sm:pt-0">
                     <p className="font-bold uppercase tracking-wider text-[10px] text-gray-500 mb-1">Date</p>
                     <div className="font-serif text-gray-900 text-base">{formattedDate}</div>
                </div>
            </div>
        </div>

        {/* BODY */}
        <div className="prose prose-lg max-w-none">
             {isEditing ? (
                 <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="w-full min-h-[500px] whitespace-pre-wrap font-serif text-gray-900 leading-loose text-justify text-base md:text-lg border-2 border-blue-300 focus:outline-none focus:border-blue-600 bg-gray-50 p-4 rounded resize-y"
                 />
             ) : (
                <div className="whitespace-pre-wrap font-serif text-gray-900 leading-loose text-justify text-base md:text-lg">
                    {project.content}
                </div>
             )}
        </div>

        {/* FOOTER */}
        <div className="mt-20 pt-6 border-t border-gray-300 flex flex-col sm:flex-row justify-between items-center text-[10px] text-gray-400 font-sans uppercase tracking-widest gap-2 print:fixed print:bottom-10 print:left-0 print:w-full print:px-[20mm]">
            <span>ProjectBuddy AI Generation</span>
            <span>Official Submission Document</span>
        </div>

      </div>
    </div>
  );
};

export default ProjectResult;
